services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_2
    volumes:
      - /Users/saurabhborsiwala/SRE_Training/task-2/Docker/backend/Data/postgresql/data:/var/lib/postgresql/data
    ports:
      - 5432:5432      
    networks:
      app_net:
        ipv4_address: 192.168.0.2

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      app_net:
        ipv4_address: 192.168.0.3
  
  backend_spring:
    container_name: backend_spring
    build:
      context: ./backend/java_spring_boot/task_2
      dockerfile: dockerfile.spring
    command: java -jar /app.jar
    ports:
      - 8081:8080
    networks:
      app_net:
        ipv4_address: 192.168.0.7
  
  backend_python:
    build:
      context: ./backend/python
      dockerfile: dockerfile.python
    command: python manage.py runserver 0.0.0.0:8080
    ports:
      - 8080:8080
    container_name: python-django
    networks:
      app_net:
        ipv4_address: 192.168.0.5
    depends_on:
      - db

  frontend:
    container_name: react
    build:
      context: ./frontend
      dockerfile: dockerfile.react
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    networks:
      app_net:
        ipv4_address: 192.168.0.6
        

networks:
  app_net:
    name: network_1
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"
          gateway: 192.168.0.1