# Generated by Django 4.2.14 on 2024-07-20 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
    ]
