# Generated by Django 5.0.7 on 2024-08-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enduser",
            name="face_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
