# Generated by Django 5.0.7 on 2024-08-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image", models.ImageField(upload_to="product_images/")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("mobile", "Mobile Phone"),
                            ("watch", "Smart Watch"),
                            ("laptop", "Laptop"),
                            ("pc", "PC"),
                            ("ipad", "iPad"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "product",
            },
        ),
    ]
